/**
 * Field for storing range data.
 *
 * Its `static prepareData` derives `scalar` (boolean) and a `labels` bag onto the
 * INITIALIZED value; both are surfaced on {@link RangeField.RangeData} for downstream reuse.
 */

declare global {
  namespace dnd5e.types.fields {
    type RangeField<Fields extends foundry.data.fields.DataSchema = {}> =
      foundry.data.fields.SchemaField<dnd5e.types.MergeSchemas<dnd5e.types.fields.RangeField.Schema, Fields>>;

    namespace RangeField {
      interface Schema extends foundry.data.fields.DataSchema {
        value: dnd5e.types.fields.FormulaField<{ deterministic: true }>;
        units: dnd5e.types.fields.RestrictedStringField<dnd5e.types.RangeType.TypeKey | dnd5e.types.DistanceUnit.TypeKey, { required: true; blank: false; initial: "self" }>;
        special: foundry.data.fields.StringField;
      }

      /** Labels generated by `prepareData`. */
      interface Labels {
        range?: string;
        rangeParts?: string;
        description?: string;
      }

      /**
       * The `range` shape after `prepareData`: the initialized source plus the derived
       * `scalar` flag and `labels` bag. `value` becomes `null` when non-scalar.
       */
      type RangeData = dnd5e.types.PrettifyType<
        dnd5e.types.InitializedOf<Schema> & {
          scalar: boolean;
          labels: dnd5e.types.fields.RangeField.Labels;
        }
      >;
    }
  }
}

declare class RangeField<
  Fields extends foundry.data.fields.DataSchema = {},
> extends foundry.data.fields.SchemaField<
  dnd5e.types.MergeSchemas<dnd5e.types.fields.RangeField.Schema, Fields>
> {
  /**
   * Prepare data for this field. Should be called during the `prepareFinalData` stage.
   * @this {ItemDataModel | BaseActivityData}
   * @param rollData - Roll data used for formula replacements.
   * @param labels   - Object in which to insert generated labels.
   */
  static prepareData(
    rollData: dnd5e.types.documents.ItemRollData | dnd5e.types.documents.ActivityRollData,
    labels?: object,
  ): void;
}

export { RangeField };
export {};
