/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.settings` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.settings {
    const BaseSettingsConfig: typeof import("../applications/settings/base-settings.mjs").default;
    type BaseSettingsConfig = import("../applications/settings/base-settings.mjs").default;
    const BastionSettingsConfig: typeof import("../applications/settings/bastion-settings.mjs").default;
    type BastionSettingsConfig = import("../applications/settings/bastion-settings.mjs").default;
    const CalendarSettingsConfig: typeof import("../applications/settings/calendar-settings.mjs").default;
    type CalendarSettingsConfig = import("../applications/settings/calendar-settings.mjs").default;
    const CompendiumBrowserSettingsConfig: typeof import("../applications/settings/compendium-browser-settings.mjs").default;
    type CompendiumBrowserSettingsConfig = import("../applications/settings/compendium-browser-settings.mjs").default;
    const VisibilitySettingsConfig: typeof import("../applications/settings/visibility-settings.mjs").default;
    type VisibilitySettingsConfig = import("../applications/settings/visibility-settings.mjs").default;
    namespace sidebar {
      const renderSettings: typeof import("../applications/settings/sidebar.mjs").renderSettings;
    }
  }
}

export {};
