/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.journal` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.journal {
    const JournalClassPageSheet: typeof import("../applications/journal/class-page-sheet.mjs").default;
    type JournalClassPageSheet = import("../applications/journal/class-page-sheet.mjs").default;
    const JournalEditor: typeof import("../applications/journal/journal-editor.mjs").default;
    type JournalEditor = import("../applications/journal/journal-editor.mjs").default;
    const JournalMapLocationPageSheet: typeof import("../applications/journal/map-page-sheet.mjs").default;
    type JournalMapLocationPageSheet = import("../applications/journal/map-page-sheet.mjs").default;
    const JournalRulePageSheet: typeof import("../applications/journal/rule-page-sheet.mjs").default;
    type JournalRulePageSheet = import("../applications/journal/rule-page-sheet.mjs").default;
    const JournalSheet5e: typeof import("../applications/journal/journal-sheet.mjs").default;
    type JournalSheet5e = import("../applications/journal/journal-sheet.mjs").default;
    const JournalEntrySheet5e: typeof import("../applications/journal/journal-entry-sheet.mjs").default;
    type JournalEntrySheet5e = import("../applications/journal/journal-entry-sheet.mjs").default;
    const JournalSpellListPageSheet: typeof import("../applications/journal/spells-page-sheet.mjs").default;
    type JournalSpellListPageSheet = import("../applications/journal/spells-page-sheet.mjs").default;
    const TableOfContentsCompendium: typeof import("../applications/journal/table-of-contents.mjs").default;
    type TableOfContentsCompendium = import("../applications/journal/table-of-contents.mjs").default;
    const CompendiumTOCConfig: typeof import("../applications/journal/config/compendium-toc-config.mjs").default;
    type CompendiumTOCConfig = import("../applications/journal/config/compendium-toc-config.mjs").default;
    const JournalNavigationConfig: typeof import("../applications/journal/config/journal-navigation-config.mjs").default;
    type JournalNavigationConfig = import("../applications/journal/config/journal-navigation-config.mjs").default;
    const JournalTOCConfig: typeof import("../applications/journal/config/journal-toc-config.mjs").default;
    type JournalTOCConfig = import("../applications/journal/config/journal-toc-config.mjs").default;
  }
}

export {};
