/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.combat` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.combat {
    const CombatTracker5e: typeof import("../applications/combat/combat-tracker.mjs").default;
    type CombatTracker5e = import("../applications/combat/combat-tracker.mjs").default;
  }
}

export {};
