/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.actor` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.actor {
    const BastionAttackDialog: typeof import("../applications/actor/bastion-attack-dialog.mjs").default;
    type BastionAttackDialog = import("../applications/actor/bastion-attack-dialog.mjs").default;
    const CharacterActorSheet: typeof import("../applications/actor/character-sheet.mjs").default;
    type CharacterActorSheet = import("../applications/actor/character-sheet.mjs").default;
    const EncounterActorSheet: typeof import("../applications/actor/encounter-sheet.mjs").default;
    type EncounterActorSheet = import("../applications/actor/encounter-sheet.mjs").default;
    const GroupActorSheet: typeof import("../applications/actor/group-sheet.mjs").default;
    type GroupActorSheet = import("../applications/actor/group-sheet.mjs").default;
    const NPCActorSheet: typeof import("../applications/actor/npc-sheet.mjs").default;
    type NPCActorSheet = import("../applications/actor/npc-sheet.mjs").default;
    const PartyRequestDialog: typeof import("../applications/actor/party-request-dialog.mjs").default;
    type PartyRequestDialog = import("../applications/actor/party-request-dialog.mjs").default;
    const TransformDialog: typeof import("../applications/actor/transform-dialog.mjs").default;
    type TransformDialog = import("../applications/actor/transform-dialog.mjs").default;
    const VehicleActorSheet: typeof import("../applications/actor/vehicle-sheet.mjs").default;
    type VehicleActorSheet = import("../applications/actor/vehicle-sheet.mjs").default;
    const BaseActorSheet: typeof import("../applications/actor/api/base-actor-sheet.mjs").default;
    type BaseActorSheet = import("../applications/actor/api/base-actor-sheet.mjs").default;
    const BaseConfigSheetV2: typeof import("../applications/actor/api/base-config-sheet.mjs").default;
    type BaseConfigSheetV2 = import("../applications/actor/api/base-config-sheet.mjs").default;
    const MultiActorSheet: typeof import("../applications/actor/api/multi-actor-sheet.mjs").default;
    type MultiActorSheet = import("../applications/actor/api/multi-actor-sheet.mjs").default;
    const AbilityConfig: typeof import("../applications/actor/config/ability-config.mjs").default;
    type AbilityConfig = import("../applications/actor/config/ability-config.mjs").default;
    const ArmorClassConfig: typeof import("../applications/actor/config/armor-class-config.mjs").default;
    type ArmorClassConfig = import("../applications/actor/config/armor-class-config.mjs").default;
    const BaseProficiencyConfig: typeof import("../applications/actor/config/base-proficiency-config.mjs").default;
    type BaseProficiencyConfig = import("../applications/actor/config/base-proficiency-config.mjs").default;
    const ConcentrationConfig: typeof import("../applications/actor/config/concentration-config.mjs").default;
    type ConcentrationConfig = import("../applications/actor/config/concentration-config.mjs").default;
    const DamagesConfig: typeof import("../applications/actor/config/damages-config.mjs").default;
    type DamagesConfig = import("../applications/actor/config/damages-config.mjs").default;
    const DeathConfig: typeof import("../applications/actor/config/death-config.mjs").default;
    type DeathConfig = import("../applications/actor/config/death-config.mjs").default;
    const HabitatConfig: typeof import("../applications/actor/config/habitat-config.mjs").default;
    type HabitatConfig = import("../applications/actor/config/habitat-config.mjs").default;
    const HitDiceConfig: typeof import("../applications/actor/config/hit-dice-config.mjs").default;
    type HitDiceConfig = import("../applications/actor/config/hit-dice-config.mjs").default;
    const HitPointsConfig: typeof import("../applications/actor/config/hit-points-config.mjs").default;
    type HitPointsConfig = import("../applications/actor/config/hit-points-config.mjs").default;
    const InitiativeConfig: typeof import("../applications/actor/config/initiative-config.mjs").default;
    type InitiativeConfig = import("../applications/actor/config/initiative-config.mjs").default;
    const LanguagesConfig: typeof import("../applications/actor/config/languages-config.mjs").default;
    type LanguagesConfig = import("../applications/actor/config/languages-config.mjs").default;
    const SkillToolConfig: typeof import("../applications/actor/config/skill-tool-config.mjs").default;
    type SkillToolConfig = import("../applications/actor/config/skill-tool-config.mjs").default;
    const SkillsConfig: typeof import("../applications/actor/config/skills-config.mjs").default;
    type SkillsConfig = import("../applications/actor/config/skills-config.mjs").default;
    const SpellSlotsConfig: typeof import("../applications/actor/config/spell-slots-config.mjs").default;
    type SpellSlotsConfig = import("../applications/actor/config/spell-slots-config.mjs").default;
    const ToolsConfig: typeof import("../applications/actor/config/tools-config.mjs").default;
    type ToolsConfig = import("../applications/actor/config/tools-config.mjs").default;
    const TraitsConfig: typeof import("../applications/actor/config/traits-config.mjs").default;
    type TraitsConfig = import("../applications/actor/config/traits-config.mjs").default;
    const TreasureConfig: typeof import("../applications/actor/config/treasure-config.mjs").default;
    type TreasureConfig = import("../applications/actor/config/treasure-config.mjs").default;
    const WeaponsConfig: typeof import("../applications/actor/config/weapons-config.mjs").default;
    type WeaponsConfig = import("../applications/actor/config/weapons-config.mjs").default;
    const BaseRestDialog: typeof import("../applications/actor/rest/base-rest-dialog.mjs").default;
    type BaseRestDialog = import("../applications/actor/rest/base-rest-dialog.mjs").default;
    const LongRestDialog: typeof import("../applications/actor/rest/long-rest-dialog.mjs").default;
    type LongRestDialog = import("../applications/actor/rest/long-rest-dialog.mjs").default;
    const ShortRestDialog: typeof import("../applications/actor/rest/short-rest-dialog.mjs").default;
    type ShortRestDialog = import("../applications/actor/rest/short-rest-dialog.mjs").default;
  }
}

export {};
