/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.components` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.components {
    const ActivitiesElement: typeof import("../applications/components/activities.mjs").default;
    type ActivitiesElement = import("../applications/components/activities.mjs").default;
    const AdoptedStyleSheetMixin: typeof import("../applications/components/adopted-stylesheet-mixin.mjs").default;
    const CopyableTextElement: typeof import("../applications/components/copyable-text.mjs").default;
    type CopyableTextElement = import("../applications/components/copyable-text.mjs").default;
    const CheckboxElement: typeof import("../applications/components/checkbox.mjs").default;
    type CheckboxElement = import("../applications/components/checkbox.mjs").default;
    const DamageApplicationElement: typeof import("../applications/components/damage-application.mjs").default;
    type DamageApplicationElement = import("../applications/components/damage-application.mjs").default;
    const DoubleRangePickerElement: typeof import("../applications/components/double-range-picker.mjs").default;
    type DoubleRangePickerElement = import("../applications/components/double-range-picker.mjs").default;
    const EffectApplicationElement: typeof import("../applications/components/effect-application.mjs").default;
    type EffectApplicationElement = import("../applications/components/effect-application.mjs").default;
    const EffectsElement: typeof import("../applications/components/effects.mjs").default;
    type EffectsElement = import("../applications/components/effects.mjs").default;
    const EnchantmentApplicationElement: typeof import("../applications/components/enchantment-application.mjs").default;
    type EnchantmentApplicationElement = import("../applications/components/enchantment-application.mjs").default;
    const FiligreeBoxElement: typeof import("../applications/components/filigree-box.mjs").default;
    type FiligreeBoxElement = import("../applications/components/filigree-box.mjs").default;
    const FilterStateElement: typeof import("../applications/components/filter-state.mjs").default;
    type FilterStateElement = import("../applications/components/filter-state.mjs").default;
    const IconElement: typeof import("../applications/components/icon.mjs").default;
    type IconElement = import("../applications/components/icon.mjs").default;
    const IdentifierInputElement: typeof import("../applications/components/identifier-input.mjs").default;
    type IdentifierInputElement = import("../applications/components/identifier-input.mjs").default;
    const InventoryElement: typeof import("../applications/components/inventory.mjs").default;
    type InventoryElement = import("../applications/components/inventory.mjs").default;
    const ItemListControlsElement: typeof import("../applications/components/item-list-controls.mjs").default;
    type ItemListControlsElement = import("../applications/components/item-list-controls.mjs").default;
    const ProficiencyCycleElement: typeof import("../applications/components/proficiency-cycle.mjs").default;
    type ProficiencyCycleElement = import("../applications/components/proficiency-cycle.mjs").default;
    const SlideToggleElement: typeof import("../applications/components/slide-toggle.mjs").default;
    type SlideToggleElement = import("../applications/components/slide-toggle.mjs").default;
  }
}

export {};
