/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.item` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.item {
    const ContainerSheet: typeof import("../applications/item/container-sheet.mjs").default;
    type ContainerSheet = import("../applications/item/container-sheet.mjs").default;
    const ItemCompendium5e: typeof import("../applications/item/item-compendium.mjs").default;
    type ItemCompendium5e = import("../applications/item/item-compendium.mjs").default;
    const ItemDirectory5e: typeof import("../applications/item/item-directory.mjs").default;
    type ItemDirectory5e = import("../applications/item/item-directory.mjs").default;
    const ItemSheet5e: typeof import("../applications/item/item-sheet.mjs").default;
    type ItemSheet5e = import("../applications/item/item-sheet.mjs").default;
    const StartingEquipmentConfig: typeof import("../applications/item/config/starting-equipment-config.mjs").default;
    type StartingEquipmentConfig = import("../applications/item/config/starting-equipment-config.mjs").default;
  }
}

export {};
