/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.regionBehavior` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.regionBehavior {
    const DifficultTerrainConfig: typeof import("../applications/region-behavior/difficult-terrain-config.mjs").default;
    type DifficultTerrainConfig = import("../applications/region-behavior/difficult-terrain-config.mjs").default;
    const RotateAreaConfig: typeof import("../applications/region-behavior/rotate-area-config.mjs").default;
    type RotateAreaConfig = import("../applications/region-behavior/rotate-area-config.mjs").default;
  }
}

export {};
