/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.advancement` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.advancement {
    const AdvancementConfig: typeof import("../applications/advancement/advancement-config.mjs").default;
    type AdvancementConfig = import("../applications/advancement/advancement-config.mjs").default;
    const AdvancementConfigV2: typeof import("../applications/advancement/advancement-config-v2.mjs").default;
    type AdvancementConfigV2 = import("../applications/advancement/advancement-config-v2.mjs").default;
    const AdvancementConfirmationDialog: typeof import("../applications/advancement/advancement-confirmation-dialog.mjs").default;
    type AdvancementConfirmationDialog = import("../applications/advancement/advancement-confirmation-dialog.mjs").default;
    const AdvancementFlow: typeof import("../applications/advancement/advancement-flow.mjs").default;
    type AdvancementFlow = import("../applications/advancement/advancement-flow.mjs").default;
    const AdvancementFlowV2: typeof import("../applications/advancement/advancement-flow-v2.mjs").default;
    type AdvancementFlowV2 = import("../applications/advancement/advancement-flow-v2.mjs").default;
    const AdvancementManager: typeof import("../applications/advancement/advancement-manager.mjs").default;
    type AdvancementManager = import("../applications/advancement/advancement-manager.mjs").default;
    const AdvancementMigrationDialog: typeof import("../applications/advancement/advancement-migration-dialog.mjs").default;
    type AdvancementMigrationDialog = import("../applications/advancement/advancement-migration-dialog.mjs").default;
    const AbilityScoreImprovementConfig: typeof import("../applications/advancement/ability-score-improvement-config.mjs").default;
    type AbilityScoreImprovementConfig = import("../applications/advancement/ability-score-improvement-config.mjs").default;
    const AbilityScoreImprovementFlow: typeof import("../applications/advancement/ability-score-improvement-flow.mjs").default;
    type AbilityScoreImprovementFlow = import("../applications/advancement/ability-score-improvement-flow.mjs").default;
    const HitPointsConfig: typeof import("../applications/advancement/hit-points-config.mjs").default;
    type HitPointsConfig = import("../applications/advancement/hit-points-config.mjs").default;
    const HitPointsFlow: typeof import("../applications/advancement/hit-points-flow.mjs").default;
    type HitPointsFlow = import("../applications/advancement/hit-points-flow.mjs").default;
    const ItemChoiceConfig: typeof import("../applications/advancement/item-choice-config.mjs").default;
    type ItemChoiceConfig = import("../applications/advancement/item-choice-config.mjs").default;
    const ItemChoiceFlow: typeof import("../applications/advancement/item-choice-flow.mjs").default;
    type ItemChoiceFlow = import("../applications/advancement/item-choice-flow.mjs").default;
    const ItemGrantConfig: typeof import("../applications/advancement/item-grant-config.mjs").default;
    type ItemGrantConfig = import("../applications/advancement/item-grant-config.mjs").default;
    const ItemGrantFlow: typeof import("../applications/advancement/item-grant-flow.mjs").default;
    type ItemGrantFlow = import("../applications/advancement/item-grant-flow.mjs").default;
    const ItemGrantFlowV2: typeof import("../applications/advancement/item-grant-flow-v2.mjs").default;
    type ItemGrantFlowV2 = import("../applications/advancement/item-grant-flow-v2.mjs").default;
    const ModifyItemConfig: typeof import("../applications/advancement/modify-item-config.mjs").default;
    type ModifyItemConfig = import("../applications/advancement/modify-item-config.mjs").default;
    const ModifyItemFlow: typeof import("../applications/advancement/modify-item-flow.mjs").default;
    type ModifyItemFlow = import("../applications/advancement/modify-item-flow.mjs").default;
    const ScaleValueConfig: typeof import("../applications/advancement/scale-value-config.mjs").default;
    type ScaleValueConfig = import("../applications/advancement/scale-value-config.mjs").default;
    const ScaleValueFlow: typeof import("../applications/advancement/scale-value-flow.mjs").default;
    type ScaleValueFlow = import("../applications/advancement/scale-value-flow.mjs").default;
    const SizeConfig: typeof import("../applications/advancement/size-config.mjs").default;
    type SizeConfig = import("../applications/advancement/size-config.mjs").default;
    const SizeFlow: typeof import("../applications/advancement/size-flow.mjs").default;
    type SizeFlow = import("../applications/advancement/size-flow.mjs").default;
    const SubclassFlow: typeof import("../applications/advancement/subclass-flow.mjs").default;
    type SubclassFlow = import("../applications/advancement/subclass-flow.mjs").default;
    const TraitConfig: typeof import("../applications/advancement/trait-config.mjs").default;
    type TraitConfig = import("../applications/advancement/trait-config.mjs").default;
    const TraitFlow: typeof import("../applications/advancement/trait-flow.mjs").default;
    type TraitFlow = import("../applications/advancement/trait-flow.mjs").default;
  }
}

export {};
