/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications {
    const Award: typeof import("../applications/award.mjs").default;
    type Award = import("../applications/award.mjs").default;
    const ChatLog5e: typeof import("../applications/chat-log.mjs").default;
    type ChatLog5e = import("../applications/chat-log.mjs").default;
    const CompendiumBrowser: typeof import("../applications/compendium-browser.mjs").default;
    type CompendiumBrowser = import("../applications/compendium-browser.mjs").default;
    const ContextMenu5e: typeof import("../applications/context-menu.mjs").default;
    type ContextMenu5e = import("../applications/context-menu.mjs").default;
    const CreateDocumentDialog: typeof import("../applications/create-document-dialog.mjs").default;
    type CreateDocumentDialog = import("../applications/create-document-dialog.mjs").default;
    const CurrencyManager: typeof import("../applications/currency-manager.mjs").default;
    type CurrencyManager = import("../applications/currency-manager.mjs").default;
    const DialogMixin: typeof import("../applications/dialog-mixin.mjs").default;
    const PropertyAttribution: typeof import("../applications/property-attribution.mjs").default;
    type PropertyAttribution = import("../applications/property-attribution.mjs").default;
    const RollTableSheet5e: typeof import("../applications/roll-table-sheet.mjs").default;
    type RollTableSheet5e = import("../applications/roll-table-sheet.mjs").default;
    const Tabs5e: typeof import("../applications/tabs.mjs").default;
    type Tabs5e = import("../applications/tabs.mjs").default;
    const SheetConfig: typeof import("../applications/sheet-config.mjs").default;
    type SheetConfig = import("../applications/sheet-config.mjs").default;
    const PrototypeTokenConfig5e: typeof import("../applications/token-config.mjs").PrototypeTokenConfig5e;
    type PrototypeTokenConfig5e<
      RenderContext extends foundry.applications.sheets.PrototypeTokenConfig.RenderContext = import("../applications/token-config.mjs").PrototypeTokenConfig5e.RenderContext,
      Configuration extends foundry.applications.sheets.PrototypeTokenConfig.Configuration = import("../applications/token-config.mjs").PrototypeTokenConfig5e.Configuration,
      RenderOptions extends foundry.applications.sheets.PrototypeTokenConfig.RenderOptions = import("../applications/token-config.mjs").PrototypeTokenConfig5e.RenderOptions,
    > = import("../applications/token-config.mjs").PrototypeTokenConfig5e<RenderContext, Configuration, RenderOptions>;
    const TokenConfig5e: typeof import("../applications/token-config.mjs").TokenConfig5e;
    type TokenConfig5e<
      RenderContext extends foundry.applications.sheets.TokenConfig.RenderContext = import("../applications/token-config.mjs").TokenConfig5e.RenderContext,
      Configuration extends foundry.applications.sheets.TokenConfig.Configuration = import("../applications/token-config.mjs").TokenConfig5e.Configuration,
      RenderOptions extends foundry.applications.sheets.TokenConfig.RenderOptions = import("../applications/token-config.mjs").TokenConfig5e.RenderOptions,
    > = import("../applications/token-config.mjs").TokenConfig5e<RenderContext, Configuration, RenderOptions>;
  }
}

export {};
