/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.calendar` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.calendar {
    const BaseCalendarHUD: typeof import("../applications/calendar/base-calendar-hud.mjs").default;
    type BaseCalendarHUD = import("../applications/calendar/base-calendar-hud.mjs").default;
    const CalendarHUD: typeof import("../applications/calendar/calendar-hud.mjs").default;
    type CalendarHUD = import("../applications/calendar/calendar-hud.mjs").default;
    const SetDateDialog: typeof import("../applications/calendar/set-date-dialog.mjs").default;
    type SetDateDialog = import("../applications/calendar/set-date-dialog.mjs").default;
  }
}

export {};
