/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.activity` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.activity {
    const ActivitySheet: typeof import("../applications/activity/activity-sheet.mjs").default;
    type ActivitySheet = import("../applications/activity/activity-sheet.mjs").default;
    const AttackSheet: typeof import("../applications/activity/attack-sheet.mjs").default;
    type AttackSheet = import("../applications/activity/attack-sheet.mjs").default;
    const CastSheet: typeof import("../applications/activity/cast-sheet.mjs").default;
    type CastSheet = import("../applications/activity/cast-sheet.mjs").default;
    const CheckSheet: typeof import("../applications/activity/check-sheet.mjs").default;
    type CheckSheet = import("../applications/activity/check-sheet.mjs").default;
    const DamageSheet: typeof import("../applications/activity/damage-sheet.mjs").default;
    type DamageSheet = import("../applications/activity/damage-sheet.mjs").default;
    const EnchantSheet: typeof import("../applications/activity/enchant-sheet.mjs").default;
    type EnchantSheet = import("../applications/activity/enchant-sheet.mjs").default;
    const ForwardSheet: typeof import("../applications/activity/forward-sheet.mjs").default;
    type ForwardSheet = import("../applications/activity/forward-sheet.mjs").default;
    const HealSheet: typeof import("../applications/activity/heal-sheet.mjs").default;
    type HealSheet = import("../applications/activity/heal-sheet.mjs").default;
    const SaveSheet: typeof import("../applications/activity/save-sheet.mjs").default;
    type SaveSheet = import("../applications/activity/save-sheet.mjs").default;
    const SummonSheet: typeof import("../applications/activity/summon-sheet.mjs").default;
    type SummonSheet = import("../applications/activity/summon-sheet.mjs").default;
    const TransformSheet: typeof import("../applications/activity/transform-sheet.mjs").default;
    type TransformSheet = import("../applications/activity/transform-sheet.mjs").default;
    const UtilitySheet: typeof import("../applications/activity/utility-sheet.mjs").default;
    type UtilitySheet = import("../applications/activity/utility-sheet.mjs").default;
    const ActivityChoiceDialog: typeof import("../applications/activity/activity-choice-dialog.mjs").default;
    type ActivityChoiceDialog = import("../applications/activity/activity-choice-dialog.mjs").default;
    const ActivityUsageDialog: typeof import("../applications/activity/activity-usage-dialog.mjs").default;
    type ActivityUsageDialog = import("../applications/activity/activity-usage-dialog.mjs").default;
    const EnchantUsageDialog: typeof import("../applications/activity/enchant-usage-dialog.mjs").default;
    type EnchantUsageDialog = import("../applications/activity/enchant-usage-dialog.mjs").default;
    const OrderUsageDialog: typeof import("../applications/activity/order-usage-dialog.mjs").default;
    type OrderUsageDialog = import("../applications/activity/order-usage-dialog.mjs").default;
    const SummonUsageDialog: typeof import("../applications/activity/summon-usage-dialog.mjs").default;
    type SummonUsageDialog = import("../applications/activity/summon-usage-dialog.mjs").default;
    const TransformUsageDialog: typeof import("../applications/activity/transform-usage-dialog.mjs").default;
    type TransformUsageDialog = import("../applications/activity/transform-usage-dialog.mjs").default;
  }
}

export {};
