/**
 * AUTO-GENERATED by scripts/gen-applications-api.mjs — do not edit by hand.
 * API surface for `dnd5e.applications.dice` (mirrors the runtime _module.mjs public exports).
 */

declare global {
  namespace dnd5e.applications.dice {
    const AttackRollConfigurationDialog: typeof import("../applications/dice/attack-configuration-dialog.mjs").default;
    type AttackRollConfigurationDialog = import("../applications/dice/attack-configuration-dialog.mjs").default;
    const D20RollConfigurationDialog: typeof import("../applications/dice/d20-configuration-dialog.mjs").default;
    type D20RollConfigurationDialog = import("../applications/dice/d20-configuration-dialog.mjs").default;
    const DamageRollConfigurationDialog: typeof import("../applications/dice/damage-configuration-dialog.mjs").default;
    type DamageRollConfigurationDialog = import("../applications/dice/damage-configuration-dialog.mjs").default;
    const RollConfigurationDialog: typeof import("../applications/dice/roll-configuration-dialog.mjs").default;
    type RollConfigurationDialog = import("../applications/dice/roll-configuration-dialog.mjs").default;
    const SkillToolRollConfigurationDialog: typeof import("../applications/dice/skill-tool-configuration-dialog.mjs").default;
    type SkillToolRollConfigurationDialog = import("../applications/dice/skill-tool-configuration-dialog.mjs").default;
  }
}

export {};
